 const CONVERSATION = {
  ARCHIVE: 'ARCHIVE',
  REPORT: 'REPORT',
  DELETE: 'DELETE',
  REMOVE:'REMOVE',
  MUTE: 'MUTE',
  MARKREAD: 'MARKREAD',
  TURNOFF: 'TURNOFF',
  START: 'START',
  SETNAME: 'SETNAME'
}

export default CONVERSATION;