 const ITINERARY = {
  CREATE: 'ITINERARY_CREATE',
  SAVE: 'ITINERARY_SAVE',
  DELETE: 'ITINERARY_DELETE',
  RESET: 'ITINERARY_RESET',
  SHARE: 'ITINERARY_SHARE',
  ADD_DAY: 'ITINERARY_ADD_DAY',
  REMOVE_DAY: 'ITINERARY_REMOVE_DAY',
  ADD_ACTIVITY: 'ITINERARY_ADD_ACTIVITY',
  REMOVE_ACTIVITY: 'ITINERARY_REMOVE_ACTIVITY',
  TYPE: 'ITINERARY_TYPE',
}

export default ITINERARY;